[package]
name    = "ecc_test"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
publish = false

[dependencies]
curve25519-dalek = "1.1.3"
rand_os          = "0.1.3"

[dependencies.subtle]
version = "2"
features = ["nightly"]
